services:
  gateway:
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # 개발 테스트를 위해 임시로 localhost 주소 사용
      - USER_SERVICE_URL=http://localhost:8001
      - PRODUCT_SERVICE_URL=http://localhost:8002
      - ORDER_SERVICE_URL=http://localhost:8003
    networks:
      - msa_network

networks:
  msa_network:
    driver: bridge
